### ISSUE TITLE
更新后湖北省的 其它频道无法匹配啥情况

### ISSUE THREAD

**Issue by zhoujianjoe** [taksssss/PHP-EPG-Docker-Server#16]
RT 更新后湖北省其它频道无法匹配了，升级前正常。
![image](https://github.com/user-attachments/assets/93af554c-13d7-4c82-9fc0-a61004afe7e5)

**Comment by taksssss** [comment]
像是缺少频道数据，你更新数据看看，还有频道列表看看有没有这几个。我这边正常。
![微信截图_20240921021839](https://github.com/user-attachments/assets/1d78c20e-664b-4f8f-a794-3dd3fbb94784)

**Comment by zhoujianjoe** [comment]
> 像是缺少频道数据，你更新数据看看，还有频道列表看看有没有这几个。我这边正常。 ![微信截图_20240921021839](https://private-user-images.githubusercontent.com/26397391/369514319-1d78c20e-664b-4f8f-a794-3dd3fbb94784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODAzNzcsIm5iZiI6MTcyNjg4MDA3NywicGF0aCI6Ii8yNjM5NzM5MS8zNjk1MTQzMTktMWQ3OGMyMGUtNjY0Yi00ZjhmLWE3OTQtM2RkM2ZiYjk0Nzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAwNTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYmYyYTZiMmZjNTA1OWQzZjM1ZDJmMDY2YTU2ZjYzNzU1M2FjYzNiOWNkMTAzZjY2MzlhZmQzYzhlOTZlN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LZ5dOpOf7KYvg5nwinCl8sUaxbL7W7NhZXIolnU4C7c)

我用的下面的EPG数据，都是有的，https://epg.pw/xmltv/epg_CN.xml
http://epg.51zmt.top:8000/e.xml
https://epg.112114.xyz/pp.xml
https://live.fanmingming.com/e.xml

**Comment by taksssss** [comment]
嗯嗯，如果你是自己搭的php环境，建议用工具自带的定时任务，因为内置的没办法做到环境重启后拉起定时任务。
