### ISSUE TITLE
如何引用 才能生效？

### ISSUE THREAD

**Issue by kevinandlee** [taksssss/PHP-EPG-Docker-Server#17]
节目单预告，用此地址可以生效，http://epg.51zmt.top:8000/e.xml，换用我自己搭建的 http://192.168.3.1:5566/epg/t.xml （端口冲突已改），节目却确是空白。恳请指教。

**Comment by taksssss** [comment]
直接下载 t.xml 文件有数据么？

**Comment by kevinandlee** [comment]
有数据，似乎是匹配不上。

**Comment by taksssss** [comment]
xml的话，建议按照这个帖子来配置（https://www.right.com.cn/forum/thread-8392662-1-1.html）。
