### ISSUE TITLE
关于epg预告内容抓取不完整的问题，望大佬修复

### ISSUE THREAD

**Issue by hecarli555** [taksssss/PHP-EPG-Docker-Server#20]
抓取epg源为：https://live.hkdvb.com/epg/full.xml
设置已勾选全部内容
![image](https://github.com/user-attachments/assets/8501c885-9473-4906-b0a1-9dcb58ec75fa)

抓取后内容如下
![image](https://github.com/user-attachments/assets/808d4463-dbca-4d78-a57e-00d3cc658b36)

源原本内容如下
![image](https://github.com/user-attachments/assets/1d55a00d-ce2f-4fc4-8e85-0fb05f538ea8)

貌似抓取预告内容只抓取了一半，，，漏了前半段。
希望大佬能修复，感谢大佬！

**Comment by taksssss** [comment]
为啥有一部分放到su-title里面，一部分放到desc里面那么奇怪……

**Comment by hecarli555** [comment]
> 为啥有一部分放到su-title里面，一部分放到desc里面那么奇怪……

盲猜是因为预告文字太长了，所以。。。。。

**Comment by taksssss** [comment]
这个字段用得太少了，如果为了这个增加一个字段的话，有点浪费😂

**Comment by hecarli555** [comment]
> 这个字段用得太少了，如果为了这个增加一个字段的话，有点浪费😂

可是就差这个就完美了。。。看看大佬能不能大发慈悲，修改一下呢5555，感谢大佬

**Comment by hecarli555** [comment]
因为自用的tvheadend无法添加两个同类型的xml链接，想了很多办法，后来发现大佬您这个项目可以自己diy整合所有epg再导出为一个xml，现在就是差这个预告内容不完整的问题就完美了，恳请大佬出手修复，万分感谢

**Comment by taksssss** [comment]
原来的 https://live.hkdvb.com/epg/full.xml 能正常解析吗？

**Comment by hecarli555** [comment]
> 原来的 https://live.hkdvb.com/epg/full.xml 能正常解析吗？

这个链接是能正常使用也能正常显示的，这是tivimate的显示如下
![image](https://github.com/user-attachments/assets/d025edbe-33b2-4424-8046-dafa16728fbb)

**Comment by hecarli555** [comment]
目前就差这个问题就完美了，，，恳求大佬出手

**Comment by taksssss** [comment]
单单针对你这个文件，将 `update.php` 文件的
```php
'desc' => isset($programme->desc) && (string)$programme->desc !== (string)$programme->title ? (string)$programme->desc : ''
```
替换为
```php
'desc' => isset($programme->desc) && (string)$programme->desc !== (string)$programme->title ? (isset($programme->{'sub-title'}) ? (string)$programme->{'sub-title'} . (string)$programme->desc : (string)$programme->desc) : ''
```
代码不会合并进去，每次都需要你自己改。

**Comment by hecarli555** [comment]
> 单单针对你这个文件，将 `update.php` 文件的
> 
> ```
> 'desc' => isset($programme->desc) && (string)$programme->desc !== (string)$programme->title ? (string)$programme->desc : ''
> ```
> 
> 替换为
> 
> ```
> 'desc' => isset($programme->desc) && (string)$programme->desc !== (string)$programme->title ? (isset($programme->{'sub-title'}) ? (string)$programme->{'sub-title'} . (string)$programme->desc : (string)$programme->desc) : ''
> ```
> 
> 代码不会合并进去，每次升级后都需要你自己改。

首先衷心感谢大佬的帮助！真的感谢！！！
弱弱的问一句，update.php这个文件是在哪里。。。

**Comment by taksssss** [comment]
等下个版本吧，下个版本会加文件管理器。

**Comment by hecarli555** [comment]
> 新版本带文件管理器了

日了。。。用文件管理器编辑update.php替换你之前说的代码后打不开后台了。。。。这个咋办

**Comment by hecarli555** [comment]
![image](https://github.com/user-attachments/assets/30ecdb79-42a2-4e81-9531-2b5321bdf838)

另外再咨询个问题，live.hkdvb.com里面有个台叫“jade翡翠台”，112114有个叫“翡翠台”
现在我想自己本地m3u里建个”翡翠台“”的名字，而又能匹配到“jade翡翠台”的epg呢？

**Comment by hecarli555** [comment]
倘若我本地m3u里的电视台名称都带高清，例如cctv1（高清）、湖南卫视（高清），而抓取回来的epg台名字都不带“（高清）”，除了一个个改别名后，有没有更快捷的方法可以一键适配呢？

**Comment by taksssss** [comment]
首页有写。
xmltv 用户搭配 [【一键生成】匹配 M3U 文件的 XML 节目单](https://www.right.com.cn/forum/thread-8392662-1-1.html) 使用。

**Comment by taksssss** [comment]
或者在台标里面，有一个M3U转换的功能，会匹配EPG跟台标。

**Comment by hecarli555** [comment]
> > 单单针对你这个文件，将 `update.php` 文件的
> > ```
> > 'desc' => isset($programme->desc) && (string)$programme->desc !== (string)$programme->title ? (string)$programme->desc : ''
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 替换为
> > ```
> > 'desc' => isset($programme->desc) && (string)$programme->desc !== (string)$programme->title ? (isset($programme->{'sub-title'}) ? (string)$programme->{'sub-title'} . (string)$programme->desc : (string)$programme->desc) : ''
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 代码不会合并进去，每次升级后都需要你自己改。
> 
> 首先衷心感谢大佬的帮助！真的感谢！！！ 弱弱的问一句，update.php这个文件是在哪里。。。是不是需要映射出来？

大佬，再厚颜无耻的问一下，这个功能能不能集成到“更多设置”里，或者增加一个增强功能按钮，可供选择性打开呢？

**Comment by taksssss** [comment]
不会集成，因为你这个不是正常功能，代码逻辑是不对的。是你的epg源有问题，不应该分成两段的。

**Comment by hecarli555** [comment]
> 不会集成，因为你这个不是正常功能，代码逻辑是不对的。是你的epg源有问题，不应该分成两段的。

哦哦哦，好吧，明白了
