### ISSUE TITLE
有些台标频道信息里找不到。。。

### ISSUE THREAD

**Issue by hecarli555** [taksssss/PHP-EPG-Docker-Server#22]
![image](https://github.com/user-attachments/assets/fc1f13f8-2ebf-4551-aa6d-5ad2b0ddeff0)
![image](https://github.com/user-attachments/assets/24d03e9e-df01-44be-9234-7a58185acb19)

如图所示，CHC影迷电影在“台标信息”里选全显是能找到的，但是在“频道信息”里却找不到，造成使用生成的xml链接时无法匹配到图标，这种情况应该如何解决呢？

**Comment by taksssss** [comment]
建议直接在m3u文件里面匹配台标。xml的台标字段优先级挺低的，而且感觉支持的APP也不全。
这部分没节目信息的频道，不会插入到xml文件中。

**Comment by hecarli555** [comment]
> 建议直接在m3u文件里面匹配台标。xml的台标字段优先级挺低的，而且感觉支持的APP也不全。 这部分没节目信息的频道，不会插入到xml文件中。

如果是直接在m3u本地修改的话，那直接填图标的原来的来源地址就行了，自己部署epg不就是为了能有个中转服务嘛，希望就是没有epg的图标也能通过xml匹配上

**Comment by hecarli555** [comment]
> 建议直接在m3u文件里面匹配台标。xml的台标字段优先级挺低的，而且感觉支持的APP也不全。 这部分没节目信息的频道，不会插入到xml文件中。

理解这句话了，，，，刚刚深有体会了，刚刚抓取112114epg的时候，发现广东珠江没有epg信息，此时连图标也消失了。。。。。

**Comment by taksssss** [comment]
> > 建议直接在m3u文件里面匹配台标。xml的台标字段优先级挺低的，而且感觉支持的APP也不全。 这部分没节目信息的频道，不会插入到xml文件中。
> 
> 如果是直接在m3u本地修改的话，那直接填图标的原来的来源地址就行了，自己部署epg不就是为了能有个中转服务嘛，希望就是没有epg的图标也能通过xml匹配上

台标里面有上传M3U/TXT匹配的。

**Comment by taksssss** [comment]
> > 建议直接在m3u文件里面匹配台标。xml的台标字段优先级挺低的，而且感觉支持的APP也不全。 这部分没节目信息的频道，不会插入到xml文件中。
> 
> 理解这句话了，，，，刚刚深有体会了，刚刚抓取112114epg的时候，发现广东珠江没有epg信息，此时连图标也消失了。。。。。

112114的xml本身就没提供台标字段吧，说实在的，没看到几个xmltv有提供台标，估计用得很少。
